### ISSUE TITLE
How to enable tracing for all services in ASP.NET app?

### ISSUE THREAD

**Issue by nsehgal** [jaegertracing/jaeger-client-csharp#103]
Hey Guys, 

As I understand, OpenTracing.Contrib.NetCore app adds this method services.AddAutoMapper(); to enable open tracing for all services for .Net core. How to do this for ASP.NET MVC app?

Thanks.

**Comment by Falco20019** [comment]
Please have a look at the PR #96 for how to use Autofac. We want to merge it soon. 

You could also use ’GlobalTracer.Instance’ after registering your instance once with ’GlobalTracer.Register’. An example can be found [here](https://github.com/yurishkuro/opentracing-tutorial/blob/master/csharp/src/lesson03/README.md).

**Comment by nsehgal** [comment]
Thanks @Falco20019
