### ISSUE TITLE
Why do we need to run jaeger-agent on each node or VM? 

### ISSUE THREAD

**Issue by nsehgal** [jaegertracing/jaeger-client-csharp#104]
Can we push the traces to the collector directly? Does the Client Library supports that? 

Thanks.

**Comment by Falco20019** [comment]
To directly communicate with the collector, use the `JAEGER_ENDPOINT` environment variable ([see README](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/README.md#configuration-via-environment)) or when using configuration, use `HttpSender` instead of the `UdpSender`.

**Comment by nsehgal** [comment]
Cool, thanks @Falco20019 Is there any performance limitations if we do that?

**Comment by Falco20019** [comment]
AFAIK, the agent would collect some traces before doing the HTTP call which boosts also the performance. But @yurishkuro can definetly tell you more :)

**Comment by yurishkuro** [comment]
The agent mostly serves as a routing proxy. If you can setup a dns for collectors then using http directly is fine. But adaptive sampling capabilities won't work since collectors do not expose the sampling via http, only the agent does.

**Comment by nsehgal** [comment]
Got it, thanks @Falco20019 & @yurishkuro
