### ISSUE TITLE
Make setting Configuration._useTraceId128Bit public

### ISSUE THREAD

**Issue by paulomorgado** [jaegertracing/jaeger-client-csharp#112]
## Requirement

I'm building a configuration provider for `Microsoft.Extensions.Configuration.*`

## Problem

`Configuration._useTraceId128Bit` is only settable if reading from environment variables.

## Proposal

Make `Configuration._WithTraceId128Bit(bool)`

**Comment by Falco20019** [comment]
This is somewhat related to the discussion in #57 and also relates to #108 and #110

**Comment by Falco20019** [comment]
Just saw that this already was part of #94 and called `Configuration.WithTraceId128Bit(bool)` but it's still `private`.
