### ISSUE TITLE
HttpSender not sending correct Authentication header key

### ISSUE THREAD

**Issue by jamendozag** [jaegertracing/jaeger-client-csharp#113]
## Requirement - what kind of business use case are you trying to solve?
I am trying to post traces to an http endpoint that uses http authentication (either by setting user/pass or authtoken)

## Problem - what in Jaeger blocks you from solving the requirement?

The current HttpSender implementation is adding a "custom" header with an `Authorize` key, instead of the standard `Authorization` key. The encrypted value if being generated just fine. This is preventing us from using this csharp jaeger client because the server will return a 401 Error (https://tools.ietf.org/html/rfc7235#section-4.2)

Some more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Change the http header key in the HttpSender from `Authorize` to `Authorization` here: https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Senders/HttpSender.cs#L45

**Comment by Falco20019** [comment]
@jurishkuro I assume jaeger-collector is assuming Authorize instead of Authorization? Or is it listening to both headers? Don’t won’t to break support here.

**Comment by jamendozag** [comment]
As an reference, the jaeger's go client uses go's [SetBasicAuth](https://golang.org/src/net/http/request.go) (line 905) here https://github.com/jaegertracing/jaeger-client-go/blob/master/transport/http.go#L141, which ends up adding the header with the `Authorization` key as well

**Comment by yurishkuro** [comment]
I am not aware of any backend functionality for this. We used basic auth in our of our deployments, but I think it was via some custom endpoints, not part of the open source version.

@vprithvi do you know?

**Comment by Falco20019** [comment]
I rechecked the Java implementation and the also seem to use Authorization. So seems like a bug introduced when porting.

**Comment by Falco20019** [comment]
@jamendozag I just deployed the fix as v0.2.2 to NuGET. You should be able to use it soon. Thanks again for finding, reporting and fixing!
