### ISSUE TITLE
Start will add AsChildOf to an already finished span

### ISSUE THREAD

**Issue by rwkarg** [jaegertracing/jaeger-client-csharp#119]
https://github.com/jaegertracing/jaeger-client-csharp/blob/16fbedf556661d1c79d2692c2266f681a02c40c1/src/Jaeger/SpanBuilder.cs#L130

This is both surprising as well as causes issues with the main thread.

It's surprising since the previous active span has had Finish called and I would expect it to be "done", but it's still returned as _tracer.ActiveSpan.

It causes issues because I would like to instrument bootstrapping/configuration of my program where I Build/Start/Finish a span. But then if there's something within that bootstrapping that starts periodic work (for example, a Couchbase client will periodically query for config updates) then it will return from a Task.Delay to the same context so the AsyncLocalContext will always return the finished initialization span and continually append each periodic tick to that finished initialization span.

Is it intended that a call to Start/StartActive will implicitly make that span a child of an already finished span?

**Comment by rwkarg** [comment]
Looks like it's a difference between calling .Finish on the Span as opposed to .Dispose on the Scope.

I'm instrumenting async WCF infrastructure and have been passing around the Span instances but it looks like it may be more appropriate to pass around the Scope. But calling .Start returns the ISpan, not an IScope. What would be the recommended way to instrument across an async call?

Basic Code:
```
public object BeforeSendRequest(ref Message request, IClientChannel channel)
        {
                var actionName = GetActionName(null, request);

                var spanBuilder = _tracer.BuildSpan(actionName ?? "WCF Call");

                var callSpan = spanBuilder.Start();

                _tracer.Inject(callSpan.Context, BuiltinFormats.HttpHeaders,
                    new HttpRequestMessageInjectAdapter(request));

                return callSpan;
        }

public void AfterReceiveReply(ref Message reply, object correlationState)
        {
            if (!(correlationState is ISpan span))
                return;

            span.SetTag("error", reply.IsFault);

            span.Finish();
        }

**Comment by yurishkuro** [comment]
I don't know the specifics in C#, but in the Java API scopes should not be passed around, they are explicitly designed to open and close on the same thread, doing otherwise will cause leaks.

Your async example looks correct, conceptually. You don't need the new span to be active if there are not going to be any children spans added to it during the outbound call.

**Comment by rwkarg** [comment]
Taking a look at things, it appears to be an issue with the way a third-party has implemented their tracing. They have an operation (refreshing configs from the server) that could either be done inline as part of a query or periodically in the background.

The inline case is a child of the existing trace, as expected.

The periodic case is initiated on the main thread and each periodic "tick" gets a appended to the initial Initialization span that has already been finished (not expected). This is where we need to work with the third-party to get each "tick" to create it's own span that ignores the active span (it's logically a new operation each time).
