### ISSUE TITLE
Accessing GlobalTracer.IsRegistered is not thread-safe

### ISSUE THREAD

**Issue by christoph-neumann-schema-de** [jaegertracing/jaeger-client-csharp#120]
## Problem - what in Jaeger blocks you from solving the requirement?

In GlobalTracer.cs the writing to s_isRegistered is thread-save via lock(s_lock).
Problem: the accessor is not thread-safe:

public static bool IsRegistered() {
    return s_isRegistered;
}

Consequence:
I would like to initialize the GlobalTracer with something like that:
if (!OpenTracing.Util.GlobalTracer.IsRegistered())
    OpenTracing.Util.GlobalTracer.Register(Tracer);

This would not be thread-safe. It is possible that two threads get IsRegistered:=false, in parallel, and then the Register happends in parallel, which throws an unexpected exception for one of both threads.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Please make reading s_isRegistered as thread-safe as writing it.

        public static bool IsRegistered() {
            lock (s_lock);
                 return s_isRegistered;
        }

**Comment by rwkarg** [comment]
Even if the proposed lock is added around the IsRegistered method, there's nothing stopping the scenario of:

- Thread 1 calls IsRegistered() and gets false
- Thread 2 calls .Register(Tracer)
- Thread 1 calls .Register(Tracer)
  - Exception

A TryRegister that returns a bool if it actually registered would be one way to address potentially multiple threads trying to register a tracer.

Is there a real world scenario where there is such high contention on registering a tracer across multiple threads that catching and handling an exception for a race condition is actually a problem?

**Comment by yurishkuro** [comment]
is this meant for opentracing-java repository?  I don't see what it has to do with Jaeger client.

**Comment by Falco20019** [comment]
@christoph-neumann-schema-de This is related to the code base of
https://github.com/opentracing/opentracing-csharp and not Jaeger, so please Post it over there.

**Comment by christoph-neumann-schema-de** [comment]
@Falco20019 : Yes. You are absolutely right. Sorry for the confusion. I will post it there.

@rwkarg : The "high" contention is easily reached with just a few (concurrent!) NUnit Test Assemblies. I got it almost at once when I started Tracing-enabled testing.
