### ISSUE TITLE
SpanBuilder.AddReference() does not add a reference when passing referencedContext of another than SpanContext type

### ISSUE THREAD

**Issue by avkom** [jaegertracing/jaeger-client-csharp#122]
## Requirement - what kind of business use case are you trying to solve?

In our application, we have objects of `SpanContextData` that implement `ISpanContext` interface. When we pass object of `SpanContextData` type to `SpanBuilder.AddReference()` or `SpanBuilder.ChildOf()`, a new reference in not added. The reason of having `SpanContextData` is that we need to include a span context as a property into our entities, and:
 * `SpanContextData` should not have dependency on Jaeger because we do not want to make our entities dependent on Jaeger
 * `SpanContextData` should be easily serializable/deserializable because we serialize/deserialize our entities and transfer them through network

```c#
public class SpanContextData : ISpanContext
{
    public string TraceId { get; set; }
    public string SpanId { get; set; }
    public IDictionary<string, string> Baggage { get; set; }
    public IEnumerable<KeyValuePair<string, string>> GetBaggageItems() => Baggage;
}
```

## Problem - what in Jaeger blocks you from solving the requirement?

When we pass an object that implements of `ISpanContext` (but not of `SpanContext` type) to `SpanBuilder.AddReference()` or `SpanBuilder.ChildOf()`, a new reference in not added.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

When we pass an object that implements `ISpanContext` (but not of `SpanContext` type) to `SpanBuilder.AddReference()` or `SpanBuilder.ChildOf()` method, the method should convert this object to `SpanContext` type and add a new reference.

**Comment by yurishkuro** [comment]
The OpenTracing API assumes that objects implementing trace/span/span-context are the objects created by the concrete tracer implementation. Even though ISpanContext is an interface, it is an extension point to be implemented by the Tracer, not by the end user. What you are trying to do is not the intention of the AddReference API, because to support it would require the tracer to know how to serialize your additional SpanContextData when exporting the span with references to the tracing backend.

You can use span tags and logs to record additional metadata, if you want.

**Comment by avkom** [comment]
```c#
// In the first microservice
public void SendTodoItem()
{
	var entityToSend = new TodoItemEntity
	{
		Title = "Title",
		Description = "Description",
		SpanContext = GlobalTracer.Instance.ActiveSpan?.Context.ToSpanContextData()
	}
	
	_messageQueue.SendTodoItem(entityToSend);
}

// In the second microservice
public void GetAndHandleTodoItem()
{
	TodoItemEntity receivedEntity = _messageQueue.ReceiveTodoItem();
	using (GlobalTracer.Instance.BuildSpan("HandleTodoItem")
		.AsChildOf(receivedEntity.SpanContext).StartActive())
	{
		// Handle todo item here
	}
}

public class SpanContextData : ISpanContext
{
	public string TraceId { get; set; }
	public string SpanId { get; set; }
	public IDictionary<string, string> Baggage { get; set; }
	public IEnumerable<KeyValuePair<string, string>> GetBaggageItems() => Baggage;
}

public class TodoItemEntity
{
	public SpanContextData SpanContext { get; set; }
	public string Title { get; set; }
	public string Description { get; set; }
}

public static class SpanContextExtentions
{
	public static SpanContextData ToSpanContextData(this ISpanContext spanContext)
	{
		SpanContextData result = null;

		if (spanContext != null)
		{
			result = new SpanContextData
			{
				TraceId = spanContext.TraceId,
				SpanId = spanContext.SpanId,
				Baggage = spanContext.GetBaggageItems().ToDictionary(x => x.Key, x => x.Value)
			};
		}
		
		return result;
	}
}
```

**Comment by yurishkuro** [comment]
In the sender:

> SpanContext = GlobalTracer.Instance.ActiveSpan?.Context.ToSpanContextData()

Why not simply use the standard inject() method? I am not seeing how this example is different from any normal communication between services (whether via RPC or queue) - the inject/extract mechanism is universally applicable.

**Comment by avkom** [comment]
We need a POCO type to pass a span context (`SpanContextData`) through process boundaries that is simply serializable/deserializable and we want to avoid usage of `ITracer.Inject()` and `ITracer.Extract()` methods because we still need to take in account what types of carrier a particular OpenTracing library supports and we need to create special adapters to convert from this carrier types to our `SpanContextData` DTO and vice versa.

**Comment by yurishkuro** [comment]
You can Inject() into a dictionary. If it's not serializable out of the box, you  can encode it somehow. Or you can inject using binary codecs, and encode the resulting byte array. Both ways are not going to tie you to a specific implementation.

**Comment by avkom** [comment]
I agree with you: it makes sense to use `IDictionary<string, string>` instead of custom `SpanContextData` to store a span context in the entity and use `Inject()`/`Extract()` as suggested in [Lesson 3 - Tracing HTTP Requests](https://github.com/yurishkuro/opentracing-tutorial/tree/master/csharp/src/lesson03). In this case we will not loose SpanContextFlags.

**Comment by avkom** [comment]
Thanks for your clarification!
