### ISSUE TITLE
Add public read-only properties to the tracer builder

### ISSUE THREAD

**Issue by tillig** [jaegertracing/jaeger-client-csharp#124]
## Requirement - what kind of business use case are you trying to solve?

I'm working on a workaround for #121 where I create a decorator for the configured sampler and set that up during app startup. My decorator can make some sampling decisions (or add some logging, or whatever) and I can still use environment-based configuration for the default sampler types (`const` or whatever).

I envision the setup of the tracer looking like this at app startup:

```c#
services.AddSingleton<ITracer>(serviceProvider =>
{
  var logFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
  var config = Tracing.Configuration.FromEnv(logFactory);
  var tracerBuilder = config.GetTracerBuilder();
  // TODO: Make use of the environment-configured settings, just wrap the sampler.
  var accessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
  var decorator = new SamplerDecorator(tracerBuilder.Sampler, accessor);
  tracerBuilder.WithSampler(decorator);
  var tracer = tracerBuilder.Build();
  GlobalTracer.Register(tracer);
  return tracer;
})
```

## Problem - what in Jaeger blocks you from solving the requirement?

The [spot in `Configuration` that generates the `ISampler`](https://github.com/jaegertracing/jaeger-client-csharp/blob/16fbedf556661d1c79d2692c2266f681a02c40c1/src/Jaeger/Configuration.cs#L204) actually does a lot of work tying metrics to the sampler. After that, [`Tracer.Builder.WithSampler` sets a private field](https://github.com/jaegertracing/jaeger-client-csharp/blob/16fbedf556661d1c79d2692c2266f681a02c40c1/src/Jaeger/Tracer.cs#L244) and you can never access that built/wired sampler again.

You also can't re-create the mechanism manually. You can read the configuration from the environment again, but [the `Configuration.SamplerConfiguration.CreateSampler` method is internal](https://github.com/jaegertracing/jaeger-client-csharp/blob/16fbedf556661d1c79d2692c2266f681a02c40c1/src/Jaeger/Configuration.cs#L346) so you can't actually rebuild the sampler from config.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The actual `SamplerConfiguration` object exposes read-only properties with the values that are set by the builder methods (e.g., `WithParam()`). I'd like to see public read-only properties on `Tracer.Builder` that have the values set by the builder methods.

It may also be nice to have properties on the actual `Tracer` to expose the things that have been set and possibly allow post-build configuration. I could just as easily have done something like...

```c#
services.AddSingleton<ITracer>(serviceProvider =>
{
  var logFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
  var config = Tracing.Configuration.FromEnv(logFactory);
  var tracer = config.GetTracerBuilder().Build();
  var accessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
  var decorator = new SamplerDecorator(tracer.Sampler, accessor);
  tracer.Sampler = decorator;
  GlobalTracer.Register(tracer);
  return tracer;
})
```

This likely relates to #74 which asks about whether there should be constructors or only builders.

**Comment by Falco20019** [comment]
Hi @tillig, post-build configuration won‘t be allowed since the whole point of the Builder is to have imutability. But I will have a look at read-only properties.

**Comment by Falco20019** [comment]
I created PR #128 which opens up the API. Afterwards you can either create a class inheriting from `SamplerConfiguration` that knows `SamplerDecorator` which would allow to also support environment configuration:
```csharp
var config = Tracing.Configuration.FromEnv(logFactory);
config.WithSampler(InheritedSamplerConfiguration.FromEnv(loggerFactory));
```

Or you can only use the sampler directly on the `Tracer.Builder`:
```csharp
var tracerBuilder = config.GetTracerBuilder();
var accessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
var decorator = new SamplerDecorator(tracerBuilder.Sampler, accessor);
var tracer = tracerBuilder.WithSampler(decorator).Build();
```
