### ISSUE TITLE
Write-rights for @saschaholesch

### ISSUE THREAD

**Issue by Falco20019** [jaegertracing/jaeger-client-csharp#131]
## Requirement - what kind of business use case are you trying to solve?
We like to have PRs reviewed before merging them.

## Problem - what in Jaeger blocks you from solving the requirement?
@cwe1ss and @grounded042 are propably very busy right now. Therefore, no one is available for reviewing the C# specific parts of our PRs.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
I would like to add @saschaholesch as member with write-rights.

/CC @yurishkuro I know I have admin-rights and can do this myself, but I just wanted to at least have some feedback from at least another person on how to get more activity into this repo.

**Comment by yurishkuro** [comment]
I could never understand how GitHub decides on the suggestions for reviewers, on #130 I see at least 30 people suggested, but @saschaholesch is not one of them and GitHub won't allow entering the username directly. I would prefer to solve it with a "reviewer" role rather than full commit rights, since @saschaholesch hasn't been active in  this repo.

**Comment by cwe1ss** [comment]
Hm yes, I'm really sorry, but I'm in a project right now and on a really tight schedule until June so unfortunately I won't have any time to do reviews. Sorry!

**Comment by Falco20019** [comment]
@yurishkuro I think GitHub suggests people who are collaborators (at least one merged commit through PRs) or team members. For team members there are three options: Read, Write and Admin. I will try to add him with Read permission and check if he appears in the reviewer list. He has been active in the background as he is one of my employees. From an activity perspective, he also did 
https://github.com/yurishkuro/opentracing-tutorial/tree/master/csharp :)

@cwe1ss No need to be sorry or even explain yourself. We all are doing this in our spare time or because we need it in our projects. That’s just the way how Open Source works and totally understandable! Myself and surely also the community are thankful for the time you have invested so far since it‘s not something to take for granted.

**Comment by Falco20019** [comment]
Read permissions are enough for a person to appear in the reviewer list. Added him in #128 as reviewer.
