### ISSUE TITLE
NuGet API keys expired

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#137]
@Falco20019 I got this email:

> We wanted to inform you that the following API key(s) on NuGet Gallery will expire soon:
> 
> • jaeger-client-csharp - expires in 6 day(s).
> 
> Visit https://www.nuget.org/account/ApiKeys to generate a new API key(s) so that you can continue pushing packages using them.
> 
> Best regards,
> 
> NuGet Gallery
> 
> 
> Privacy Statement
> Microsoft Corporation
> One Microsoft Way
> Redmond, WA 98052 USA

I see the "regenerate" button on nuget, but I don't recall where the new generated key should go after that. Do you know how to fix it?

**Comment by Falco20019** [comment]
Please set it here: https://ci.appveyor.com/account/jaegertracing/environment/37513/settings in the API Key field of the environment.

**Comment by yurishkuro** [comment]
Thanks, done.
