### ISSUE TITLE
Support for GrpcSender

### ISSUE THREAD

**Issue by Falco20019** [jaegertracing/jaeger-client-csharp#139]
## Requirement - what kind of business use case are you trying to solve?

The new `model.proto` was defined in https://github.com/jaegertracing/jaeger/issues/904 and is accepted on GRPC port `14250` by the collector.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently not implemented in the client library.

**Comment by rstraszewski** [comment]
Isn't this endpoint created for agent - collector communication, not client library - agent? 

gRPC endpoint for Agent will be created later, in phase 3 - https://github.com/jaegertracing/jaeger/issues/773

**Comment by Falco20019** [comment]
I thought it‘s analogous to the HTTP endpoint of Thrift for that we also have the HttpSender in case the user does want to communicate directly with collector without agent.

**Comment by Falco20019** [comment]
It‘s analogous to the HTTP endpoint of Thrift for that we also have the `HttpSender` in case the user does want to communicate directly with collector without agent.

I checked again, and [`jaeger-client-go`](https://github.com/jaegertracing/jaeger-client-go#environment-variables) also supports directly talking to `jaeger-collector` over HTTP.

With `Thrift` it made a difference if you were to talk to `jaeger-agent` or `jaeger-collector` since the endpoint was different, although it's having the same API. Looking at the protos, I assume we will have a `AgentService` with a similar API, maybe using streams. In this case, we might want to add a flag to define if we want to use GRPC in `agent` or `collector` mode. Since we only have that, I would propose to only offer the collector-mode right now as default.

I am using GRPC in my project and want to get rid of the Thrift dependency as soon as possible and have no problems talking to the collector directly in my use case, so I thought there may be others who are also looking forward to this.

**Comment by rstraszewski** [comment]
Ok, I understand
