### ISSUE TITLE
Support Defer sampling state

### ISSUE THREAD

**Issue by polivbr** [jaegertracing/jaeger-client-csharp#149]
## Requirement - what kind of business use case are you trying to solve?

We have cases where we want to defer the decision to sample to a downstream service, yet still want to have trace identifiers available for correlation.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, Jaeger interprets the absence of the x-b3-sampled header as a Deny sampling state, causing it to never sample and to propagate the erroneous Deny downstream.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The x-b3-sampled header should not be interpreted as Deny if it is absent, and it should be possible to configure Jaeger with no sampler, thus allowing it to also Defer to a downstream service.

**Comment by wgtmpeters** [comment]
This would make sense to me as well. 
However how do you see this working, as you would expect only a full trace to be logged. Or would it be fine for you if only spans started after the sampled header are reported?

**Comment by polivbr** [comment]
For my purposes, having the spans start after the sample header is reported is just fine. Frankly, I'm not sure how else it could possibly work.

**Comment by Falco20019** [comment]
@yurishkuro How is this usually solved throughout the different clients? This sounds like a meta topic to me.

**Comment by yurishkuro** [comment]
It is a meta topic. Jaeger only supports deferred sampling in Node.js client, and only in one process, i.e. the uber-trace-id header does not have a representation for deferred sampling at this time.

**Comment by Falco20019** [comment]
@polivbr , can you please create an issue over at the meta repo https://github.com/jaegertracing/jaeger
