### ISSUE TITLE
Infinite span creation for Jaeger internal requests when OpenTracing.Contrib.NetCore and HttpSender are used

### ISSUE THREAD

**Issue by bocharovf** [jaegertracing/jaeger-client-csharp#154]
## Requirement - what kind of business use case are you trying to solve?
Hide Jaeger internal request traces in Jaeger UI to simplify trace searching for customers.

## Problem - what in Jaeger blocks you from solving the requirement?
If JAEGER_ENDPOINT property is specified Jaeger uses HttpSender to send spans via Http directly to Jaeger Collector. [OpenTracing.Contrib.NetCore package](https://github.com/opentracing-contrib/csharp-netcore) uses DiagnosticSource to intercept each Http request and build a span. It leads to infinite span creation loop because each POST request to collector with span data creates another span and cause another POST request. Huge amount of such traces make it difficult to search real user traces.

![изображение](https://user-images.githubusercontent.com/5367465/63223898-0d74fe80-c1c5-11e9-9112-94382144d7f4.png)
![изображение](https://user-images.githubusercontent.com/5367465/63223927-6d6ba500-c1c5-11e9-9a69-ec99a498a91b.png)

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Make OpenTracing.Contrib.NetCore ignore request to Jaeger Collector by specifing "ot-ignore" request property. 
It's already done in [DefaultHttpClient](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Util/DefaultHttpClient.cs) to hide receiving of sampling settings. The same could be done in [THttpClientTransport](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Thrift/netcore/Thrift/Transports/Client/THttpClientTransport.cs)

See also [HttpHandlerDiagnosticOptions](https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/CoreFx/HttpHandlerDiagnosticOptions.cs) in OpenTracing.Contrib.NetCore

**Comment by Falco20019** [comment]
As far as I understand your request, this belongs to https://github.com/opentracing-contrib/csharp-netcore and not here. So please open the issue there since the projects are not sharing one team or repository.

**Comment by bocharovf** [comment]
Well, yes, we currently use workaround you provided and it works.

But in our case we have 240+ products and approximately the same number of teams. Some of them use .net core, some of them not. Using workaround provided above, .net core teams have to deal with the details of Jaeger / OpenTracing internal implementation for .net core. While other teams (e.g. Java teams) don't need that. So we get additional ".net core only" step to configure Jaeger. 
if we could avoid it it would be great.

And the main question is - why do we solve that issue for DefaultHttpClient in Jaeger csharp client (using ot-ignore parameter) and do not want to solve it for THttpClientTransport?

**Comment by Falco20019** [comment]
Thanks for the input. I will give it another look later.
