### ISSUE TITLE
Any option to ignore request pattern?

### ISSUE THREAD

**Issue by xumix** [jaegertracing/jaeger-client-csharp#155]
Hi.
Is there any way to configure client so that it would not report some incoming/outgoing requests? For example health checks or some service calls.
Something like this:
 ```
services.Configure<HttpHandlerDiagnosticOptions>(options =>
            {
                options.IgnorePatterns.Add(x => !x.RequestUri.IsLoopback);
            });
```

**Comment by Falco20019** [comment]
It depends on what environment you are using. It sound's like you want to use ASP.NET Core. In this case, you might want to use [opentracing-contrib/csharp-netcore](https://github.com/opentracing-contrib/csharp-netcore).

There is an example on how to add ignores here:
https://github.com/opentracing-contrib/csharp-netcore/blob/master/samples/Shared/JaegerServiceCollectionExtensions.cs

**Comment by Falco20019** [comment]
@xumix Is this resolved with my answer? If yes, please close the ticket. Thanks :)

**Comment by xumix** [comment]
> @xumix Is this resolved with my answer? If yes, please close the ticket. Thanks :)

Thanks! Looks like at the moment of opening the ticket there were no sucks option.

**Comment by AntonyNET** [comment]
> > @xumix Is this resolved with my answer? If yes, please close the ticket. Thanks :)
> 
> Thanks! Looks like at the moment of opening the ticket there were no such option.

Try this. It is work for me.

services.Configure<AspNetCoreDiagnosticOptions>(options =>
            {
                options.Hosting.IgnorePatterns.Add(context=> context.Request.Path.Value.EndWith("api/status");
            });
