### ISSUE TITLE
Add icons to packages on Nuget

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#159]
The packages on Nuget (https://www.nuget.org/packages/Jaeger/) show up with a generic icon.

Can we configure the package to display the Jaeger icon?

* stackoverflow: https://stackoverflow.com/questions/38329201/how-to-add-an-icon-to-a-nuget-package
* Icon: https://en.gravatar.com/jaegertracing

cc @Falco20019 @cwe1ss

**Comment by bocharovf** [comment]
There are two ways to do that: specify icon url or embed icon in nuget package.
Embeded icon has some advantages, but requires nuget 5.3 which is not available on [AppVeyor](https://www.appveyor.com/docs/windows-images-software/) yet. So I would say we should use url for a while.
Using 256x256 png icon (like default nuget icon) hosted on github from images folder of master branch.
