### ISSUE TITLE
How to increase grpc log level?

### ISSUE THREAD

**Issue by chrsas** [jaegertracing/jaeger-client-csharp#174]
How to increase grpc log level to `Error`?
```log
2020-05-06 15:39:19	
{"level":"info","ts":1588750759.963098,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{10.32.3.11:14250 0 <nil>}] }","system":"grpc","grpc_log":true}
2020-05-06 15:39:19	
{"level":"info","ts":1588750759.9630384,"caller":"grpc/resolver_conn_wrapper.go:126","msg":"ccResolverWrapper: sending new addresses to cc: [{10.32.3.11:14250 0 <nil>}]","system":"grpc","grpc_log":true}
2020-05-06 15:39:19	
{"level":"info","ts":1588750759.9629953,"caller":"grpc/resolver_conn_wrapper.go:140","msg":"ccResolverWrapper: got new service config: ","system":"grpc","grpc_log":true}
```

**Comment by Falco20019** [comment]
GRPC logging is done through environment variables and not managed by jaeger itself. If you want to set it from code, just call `Environment.SetEnvironmentVariable("GRPC_TRACE", "all");`.

**Comment by chrsas** [comment]
In my docker file, I used these codes, but it's no effort. @Falco20019 
```
ENV GRPC_TRACE=call_error,op_failure
ENV GRPC_VERBOSITY=ERROR
```

**Comment by Falco20019** [comment]
Have your set the logger?

https://grpc.github.io/grpc/csharp/api/Grpc.Core.GrpcEnvironment.html#Grpc_Core_GrpcEnvironment_SetLogger_Grpc_Core_Logging_ILogger_

Either use the console logger or a text file logger as endpoint. Depending on your use case.

**Comment by chrsas** [comment]
In Program.cs
```cs
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(args)
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIIS()
        .UseStartup<Startup>()
        .ConfigureServices(services => {
            if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(Jaeger.Configuration.JaegerServiceName))) {
                services.AddSingleton(serviceProvider => {
                    var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
                    var tracer = Jaeger.Configuration.FromEnv(loggerFactory).GetTracer();
                    OpenTracing.Util.GlobalTracer.Register(tracer);
                    GrpcEnvironment.SetLogger(new ConsoleLogger());
                    return tracer;
                });
            }

            services.Configure<AspNetCoreDiagnosticOptions>(options => {
                options.Hosting.IgnorePatterns.Add(context =>
                    context.Request.Path == "/health" ||
                    context.Request.Path == "/info" ||
                    context.Request.Path == "/metrics"
                );

                options.Hosting.OperationNameResolver = context => {
                    return context.Request.Path;
                };
            });

            services.AddOpenTracing();
        })
        .UseSentry();

```
In Dockerfile
```
ENV GRPC_TRACE=call_error,op_failure
ENV GRPC_VERBOSITY=ERROR
```
But the log information didn't change, 99% log info is grpc, it's hard to see the business log.

![image](https://user-images.githubusercontent.com/6327955/81521991-7d429f00-937b-11ea-82a9-55d76bf452d4.png)

**Comment by Falco20019** [comment]
This sounds like a docker usage issue and not Jaeger. But I will still do my best to help you. I haven’t worked a lot with environment variables in docker images, but according to https://docs.docker.com/engine/reference/builder/ you need to separate key and value by a whitespace and not the equals sign.

Try this:
```
ENV GRPC_TRACE call_error,op_failure
ENV GRPC_VERBOSITY ERROR
```

**Comment by chrsas** [comment]
Thank you for your help. But after I replaced `=` by space, the log output still include info level.
PS: `=` is antoher form to set [environment variable](https://docs.docker.com/engine/reference/builder/#env).
In docker image, use `printenv`:
```
GRPC_VERBOSITY=ERROR
GRPC_TRACE=call_error,op_failure
...
JAEGER_SERVICE_NAME=xxx.xxx
JAEGER_PROPAGATION=jaeger,b3
...
```

**Comment by Falco20019** [comment]
I digged a bit deeper into GRPC logging for C# and found this:
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/GrpcEnvironment.cs#L55

It seems, that by setting `GrpcEnvironment.SetLogger(new ConsoleLogger());` manually, you are killing the environment check. So just comment that line out (as using console logger with verbosity from environment is the default) or manually add `GrpcEnvironment.SetLogger(new LogLevelFilterLogger(new ConsoleLogger(), LogLevel.Error, true));` if you want `Error` as default but still be able to overwrite it by environment.

**Comment by chrsas** [comment]
I tried the following 3 ways, but nothing changed.
- In `Program.cs` just used `GrpcEnvironment.SetLogger(new LogLevelFilterLogger(new ConsoleLogger(), Grpc.Core.Logging.LogLevel.Error, true));` 
- Use `GrpcEnvironment.SetLogger(new LogLevelFilterLogger(new ConsoleLogger(), Grpc.Core.Logging.LogLevel.Error, true));`  and `ENV GRPC_VERBOSITY ERROR`
- Just use `ENV GRPC_VERBOSITY ERROR`
PS: I found that `Jaeger` doesn't dependent on `Grpc.Core`.
![image](https://user-images.githubusercontent.com/6327955/81533124-357e4080-9398-11ea-9dc3-cb014041c2eb.png)

**Comment by Falco20019** [comment]
Sorry, I assumed you try using the branch from #169.

The regular releases don't use gRPC at all right now. So are you sure that it's the C# side that's adding logging entries? if you use `GrpcEnvironment.SetLogger(new NullLogger())` you can make sure that it's not C# that is creating these log entries.

**Comment by chrsas** [comment]
Thank you very much, the log was from  `K8s Jaeger Agent Sidecars`, just change it's `--log-level`.
