### ISSUE TITLE
tracking manual object

### ISSUE THREAD

**Issue by EngRajabi** [jaegertracing/jaeger-client-csharp#188]
It is possible that cases where the socket class is made manually. Tracking done?

**Comment by Falco20019** [comment]
Hi, I sadly did not understand your use case. Can you explain it in more detail? How is the class manual, where is the socket connected to?

**Comment by EngRajabi** [comment]
If the programmer uses the socket class and send and receive a series of data. Not shown in tracking

**Comment by Falco20019** [comment]
Are you using ASP.NET (Core) or a regular application?

**Comment by EngRajabi** [comment]
im using asp core 3.1.
Yes
We had to use it manually in a number of places. For example, we would send a request to a service that uses the ISO 8583 protocol

**Comment by Falco20019** [comment]
Have you already tried using https://github.com/opentracing-contrib/csharp-netcore ? This should work, even when handling the socket data yourself as it integrates with the pipeline, as long as you only write to the body of the request directly. If not, you can still create a span by using dependency injection (to get the ITracer) and basically trace it manually. The library should make sure that it gets attached to the correct trace.

**Comment by Falco20019** [comment]
Feel free to reopen if still relevant.
