### ISSUE TITLE
Is there anyway to change THttpTransport ._connectTimeout prop value?   

### ISSUE THREAD

**Issue by anilcansutaner** [jaegertracing/jaeger-client-csharp#198]
Hello , 

First of all , thank you for such a great project.  I tried to integrate csharp client to Net Framework project. When I published our code to live, we experienced with CPU spikes and thread exhaustion. I think that when the jaeger collector api doesnt work fine,  threads are waiting for 30 sec to get answer. Is there anyway to change this static value ? 

Thank you

**Comment by Falco20019** [comment]
Hi, can you please post the code snippet how you setup Jaeger since this has effects on what senders are used.

**Comment by Falco20019** [comment]
@anilcansutaner Feel free to reopen if this is still a problem.
