### ISSUE TITLE
Jaeger server loses the refrence data of spans received from csharp client when using grpc sender.

### ISSUE THREAD

**Issue by EventHorizon1024** [jaegertracing/jaeger-client-csharp#202]
Jaeger Version 1.17
nuget packages used in client:
+ Jaeger" Version="0.4.2"     
+ Jaeger.Senders.Grpc Version="0.4.2"

When I open the Trace Graph page in jaeger ui, it shows nothing due to all the refrence field of spans are all emty. 

After comparing the logic of [`JaegerGrpcSpanConverter` ](https://github.com/jaegertracing/jaeger-client-csharp/blob/e3b70cdff25dc6406883b6b0681daa10e28441de/src/Senders/Jaeger.Senders.Grpc/Protocols/JaegerGrpcSpanConverter.cs#L35) and [`JaegerThriftSpanConverter`](https://github.com/jaegertracing/jaeger-client-csharp/blob/e3b70cdff25dc6406883b6b0681daa10e28441de/src/Senders/Jaeger.Senders.Thrift/Protocols/JaegerThriftSpanConverter.cs#L30). I found the parentId of span is not sent to server in grpc sender. And parentId is used for building the refrence data in [query api](https://github.com/jaegertracing/jaeger/blob/3b34ac6bcdeb22e09a81c6244bfeed20503a383b/plugin/storage/es/spanstore/dbmodel/to_domain.go#L76).

**Comment by Falco20019** [comment]
You mostly got it right. The gRPC span is missing the parentSpanId that Thrift has. Therefore, we must add all references and must not skip the parent. Thanks for noticing!

**Comment by Falco20019** [comment]
I just release `0.4.3`. You sould be fine to just reference `Jaeger.Senders.Grpc` without additionally `Jaeger`. If you address `Jaeger`, you will also add the `Thrift` stuff which you don't need.
