### ISSUE TITLE
1.0.1 memory leaks

### ISSUE THREAD

**Issue by vanbukin** [jaegertracing/jaeger-client-csharp#215]
**Describe the bug**
Recently I have upgrade library from 1.0.0 to 1.0.1. It cause high memory pressure and GC collects. Normally my apps have up to 10x gen0 collects, 4x gen 1 collects and 2x gen2 collects. After upgrade to 1.0.1 apps become utilize up to 400 collects per minute over all generations. Downgrade to 1.0.0 solve the problem.

**Version (please complete the following information):**
 - OS: Linux (aspnetcore 5.0.6-buster-x64)
 - Jaeger version: 1.0.1
 - Deployment: k8s

**Comment by vanbukin** [comment]
Here is some dumps from app that might be helpful to debug

[linux.gcdump.zip](https://github.com/jaegertracing/jaeger-client-csharp/files/6584766/linux.gcdump.zip)
[linux.nettrace.zip](https://github.com/jaegertracing/jaeger-client-csharp/files/6584774/linux.nettrace.zip)

**Comment by Falco20019** [comment]
Hi @vanbukin, thanks for your report. The only change between 1.0.0 and 1.0.1 is the usage of the latest version of `ApacheThrift`. Do you know what objects are leaking?

**Comment by vanbukin** [comment]
@Falco20019 I cant collect full dump of process from our production environment. So I don't know. Maybe leak is not in jaeger client, but somewhere in ApacheThrift library.

**Comment by Falco20019** [comment]
Could be related to #216

**Comment by Falco20019** [comment]
@vanbukin What configuration are you using? Especially what sender?

**Comment by Falco20019** [comment]
@vanbukin Can you try if the artifacts from https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp/builds/39488632/artifacts solve your issue? There was an issue with resetting the `MemoryBuffer` which lead to lots of `Array.Resize` calls which could explain the behavior.

**Comment by vanbukin** [comment]
@Falco20019 
> What configuration are you using? Especially what sender?

`RemoteReporter` with `UdpSender : ThriftSender` that use `ThriftUdpClientTransport`

>Can you try if the artifacts from https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp/builds/39488632/artifacts solve your issue?

I need a few days to try this

**Comment by Falco20019** [comment]
I will keep it open until you had a chance to test it with the new release

**Comment by Falco20019** [comment]
@vanbukin Any update so far?

**Comment by Falco20019** [comment]
I will close this issue due to inactivity. It should be fixed with `1.0.2`
