### ISSUE TITLE
span size calculation issue

### ISSUE THREAD

**Issue by Meiri** [jaegertracing/jaeger-client-csharp#216]
im not sure its a bug, might be missing/wrong config

span size keep increasing in ThriftSender/AppendAsync

1.  basic asp.net 5.0 web api template
2.  in startup config:
`  
services.AddOpenTracing(builder => {
                builder.ConfigureAspNetCore(options => {
                    options.Hosting.IgnorePatterns.Add(x => {
                        return x.Request.Method == "GET";
                    });
                    options.Hosting.IgnorePatterns.Add(x => {
                        return x.Request.Path == "/metrics";
                    });
                });
            });
            services.AddSingleton<ITracer>(serviceProvider =>
            {
                var serviceName = serviceProvider.GetRequiredService<IWebHostEnvironment>().ApplicationName;
                var loggerFactory = serviceProvider.GetRequiredService<Microsoft.Extensions.Logging.ILoggerFactory>();

                var reporter = new RemoteReporter.Builder()
                    .WithLoggerFactory(loggerFactory)
                    .WithSender(new MyUdpSender("host", 6831))
                    .Build();

                // This will log to a default localhost installation of Jaeger.
                var tracer = new Tracer.Builder(serviceName)
                    .WithLoggerFactory(loggerFactory)
                    .WithSampler(new ConstSampler(true))
                    .WithReporter(reporter)
                    .Build();

                // Allows code that can't use DI to also access the tracer.
                if(!GlobalTracer.IsRegistered())
                    GlobalTracer.Register(tracer);

                return tracer;
            });`
3. run a couple of http to the default controller action
 when you reach spansize the is over 65K, sender exception will be thrown.

the issue is in the thrift sender base, in the getsize function
`        
public int GetSize(TBase thriftBase)
        {
            _memoryTransport.Length = 0;
            thriftBase.WriteAsync(ProtocolFactory.GetProtocol(_memoryTransport), CancellationToken.None).GetAwaiter().GetResult();
            return _memoryTransport.Length;
        }
`

my "fix" was to use a local variable instead of _memoryTransport

`        
public int GetSize(TBase thriftBase)
        {
            using (var memoryTransport = new TMemoryBufferTransport(new TConfiguration()))
            {
                thriftBase.WriteAsync(ProtocolFactory.GetProtocol(memoryTransport), CancellationToken.None).GetAwaiter().GetResult();
                return memoryTransport.Length;
            }
        }
`

im not sure its a bug, maybe config issue.

**Comment by Falco20019** [comment]
Looks like a bug. We switched from our own `MemoryTransport` implementation to the one in `ApacheThrift`. Maybe they are not behaving the same.

I will give it a look the next hours.

**Comment by Falco20019** [comment]
@Meiri Thanks for your report. This was leading to a memory leak. I fixed it on the PR and will release it as `1.0.2` as soon it's reviewed since it's a critical bug.

**Comment by Falco20019** [comment]
I just released `v1.0.2` which should resolve your issue. If you still run into issues, let us know!

**Comment by Meiri** [comment]
happy to help,
thanks for the quick response
