### ISSUE TITLE
The SetTag method in the Span class does not work.

### ISSUE THREAD

**Issue by Ghitor** [jaegertracing/jaeger-client-csharp#224]
**Describe the bug**
It is not possible to add a tag to the span

**To Reproduce**
1.  var span = new Configuration("ServiceName", new LoggerFactory()).GetTracer().BuildSpan("OperationName").StartActive(true).Span as Span;
2. span.SetTag("TagTest", "test");
3. var tags = span.GetTags();
4. tags is empty

**Comment by yurishkuro** [comment]
what sampler is in effect above? if the span is not sampled, then writing data to it is no-op.

**Comment by Falco20019** [comment]
https://dotnetfiddle.net/b0fOoM
```cs
var loggerFactory = new NullLoggerFactory();
var samplerConfig = new Configuration.SamplerConfiguration(loggerFactory)
	.WithType(ConstSampler.Type)
	.WithParam(1);
var reporterConfig = new Configuration.ReporterConfiguration(loggerFactory)
	.WithLogSpans(true);
var config = new Configuration("myServiceName", loggerFactory)
	.WithSampler(samplerConfig)
	.WithReporter(reporterConfig);

var tracer = config.GetTracer();
var span = (Span)tracer.BuildSpan("OperationName").StartActive(true).Span;
span.SetTag("TagTest", "test");

var tags = span.GetTags();
Console.WriteLine(tags.Count);
```

If you comment line 17 (`WithSampler(samplerConfig)`) out, you will see the behavior that you experienced that no tags are set.
