### ISSUE TITLE
gRPC Sender has maxPacketSize parameter but it cannot exceed gRPC core client default max message length

### ISSUE THREAD

**Issue by js8080** [jaegertracing/jaeger-client-csharp#225]
**Describe the bug**
The gRPC Sender in `Jaeger.Senders.Grpc.GrpcSender` has a constructor that takes the parameter `int maxPacketSize` and subsequent code in the GrpcSender ensures the Span being reported does not exceed this size. However, [the core gRPC Client being used](https://github.com/grpc/grpc) has its own default max message length of 4mb (`4*1024*1024`). This default max message length can be overridden by setting the `grpc.max_send_message_length` ChannelOption but unfortunately, the GrpcSender does not do this today. Therefore, if you try to use a `maxPacketSize` value greater than 4,194,304, your Span will not be reported to the Collector.

**To Reproduce**
1. When constructing your GrpcSender (such as in your `Startup.ConfigureServices()` method), pass a value larger than 4mb (4,194,304 bytes) via the `maxPacketSize` parameter.
2. Attempt to report a Span that is larger than this size.
3. The Span will not be reported to the gRPC Collector.

**Expected behavior**
The gRPC Core client allows overriding the `grpc.max_send_message_length` setting so we should set this ChannelOption when constructing the gRPC Channel.

**Screenshots**
n/a

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: Jaeger v1.21.0 but Jaeger Client C-Sharp v1.0.2
 - Deployment: Jaeger deployed via Kubernetes but traced application is running on bare metal (Linux via WSL)

**What troubleshooting steps did you try?**
Code review.

**Additional context**
The following code update shows what I _think_ needs to be added to the `Jaeger.Senders.Grpc.GrpcSender` constructor to address the issue (notice we're passing the `channelOptions` list to the `Channel` constructor:
```csharp
        /// <param name="target">If empty it will use <see cref="DefaultCollectorGrpcTarget"/>.</param>
        /// <param name="credentials">If empty it will use <see cref="ChannelCredentials.Insecure"/>.</param>
        /// <param name="maxPacketSize">If 0 it will use <see cref="MaxPacketSize"/>.</param>
        public GrpcSender(string target, ChannelCredentials credentials, int maxPacketSize)
        {
            if (string.IsNullOrEmpty(target))
            {
                target = DefaultCollectorGrpcTarget;
            }

            if (credentials == null)
            {
                credentials = ChannelCredentials.Insecure;
            }

            if (maxPacketSize == 0)
            {
                maxPacketSize = MaxPacketSize;
            }

            // Update - create list of ChannelOptions
            var channelOptions = new List<ChannelOption>()
            {
                new ChannelOption(ChannelOptions.MaxSendMessageLength, maxPacketSize)
            };

            // Update - pass channelOptions to Channel constructor
            _channel = new Channel(target, credentials, channelOptions);

            _client = new CollectorService.CollectorServiceClient(_channel);
            _maxPacketSize = maxPacketSize;
        }
```

**Comment by Falco20019** [comment]
Fixed by #226

I will add the milestone tomorrow and release a Hotfix.

**Comment by Falco20019** [comment]
I just pushed version 1.0.3 to NuGet, which will include your fix. Thanks again for the help here.

**Comment by js8080** [comment]
> I just pushed version 1.0.3 to NuGet, which will include your fix. Thanks again for the help here.

No problem whatsoever! I was happy I could contribute.
