### ISSUE TITLE
Deprecate C# client

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#230]
@Falco20019 since you're the primary maintainer of this repo, please opine.

All other Jaeger clients are being retired: https://github.com/jaegertracing/jaeger/issues/3362

The notices are up on all other client repos except this one. Changes to README look like this: https://github.com/jaegertracing/jaeger-client-java/commit/49d40135fe3ed81048f0ba55246240edc71811bf, coupled with changing the repo description like this:
![image](https://user-images.githubusercontent.com/3523016/140773876-606d8b13-a4c3-49dd-bad2-3f8956dd20fb.png)

**Comment by Falco20019** [comment]
Thanks for the trigger. I will also have a look into upgrading to OTEL in our own application. If I find issues with the migration guide, I will update the README to assist users with guiding them over. But looks straight forward so far.
