### ISSUE TITLE
Update README to match current code

### ISSUE THREAD

**Issue by grounded042** [jaegertracing/jaeger-client-csharp#37]
The README currently does not go along with all the code changes that happened in the last couple of weeks. Lets get that fixed.

**Comment by trondhindenes** [comment]
:+1: on that. I'm trying to navigate the current landscape regarding Jaeger and c# and am going in circles due to missing/outdated docs.

It looks like this project is in the middle of a big move, so I'll keep watching.

**Comment by Falco20019** [comment]
@trondhindenes sorry to hear that. Yes, we have moved just yesterday to become the official library and still have some things to update. Just send me a message and I can look into helping you break your circle so that you can move on.

**Comment by grounded042** [comment]
I'm hoping to get the README up to date this week along with a better example. When I originally wrote the example, Jaeger wasn't the main use case so we didn't hook into it. Now that it is I would like to have an example that actually hooks up to Jaeger.

@trondhindenes I'm assuming you are currently pulling in the LetsTrace packages?

**Comment by yurishkuro** [comment]
Would be great if someone wrote a .NET version of the OT tutorials using Jaeger binding

https://github.com/yurishkuro/opentracing-tutorial

**Comment by Falco20019** [comment]
I should have a bit of time this friday. So if no one else tackles it earlier, I will get it done :)
