### ISSUE TITLE
transport configuration for web api sample

### ISSUE THREAD

**Issue by trondhindenes** [jaegertracing/jaeger-client-csharp#43]
As far as I can see in the libary code, there aren't any "defaults" as to where to send traces (looking at the jaeger trhift transport class for instance). Also I cannot find any explicit definition of the required transport params in the example code, which leads me to believe that the example simply won't push traces anywhere. Is this right? It would be awesome with more explicit documentation around configuring the transport. It would also be good if debug-level stdout logging actually included endpoint info, such as `sent trace xyz to endpoint:port using protocol <proto>`

**Comment by Falco20019** [comment]
I’m sorry but the documentation is still having some holes.

The example has only the LoggingReporter configured. To get a real endpoint change the Startup.cs and set a real reporter for the IReporter transient. For this, use:
new RemoteReporter.Builder(transport).Build();

Use the transport that you need, HTTP, UDP or Thrift: https://github.com/jaegertracing/jaeger-client-csharp/tree/master/src/Jaeger.Transport.Thrift/Transport

**Comment by trondhindenes** [comment]
Gotcha, thanks for answering. Tracing is a "long game" for us, so we'll wait until documentation solidifies before attempting to do anything in c# I think.
