### ISSUE TITLE
Extend OpenTracing tutorials with .NET + Jaeger example

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#44]
https://github.com/yurishkuro/opentracing-tutorial

**Comment by Falco20019** [comment]
If anyone want's to tackle it, feel free! I will have a look at it on friday if the issue is still unresolved :)

**Comment by Falco20019** [comment]
Takes some more time then expected, since the lessons 3-4 are not so trivial to keep simple and understandable without too much ASP.NET Core code. Will have to continue next week.

**Comment by Falco20019** [comment]
I internally assigned the issue to my colleague @saschaholesch since it's a good opportunity to get him into OpenTracing and prepare the tutorial also for other of my colleagues.

**Comment by Falco20019** [comment]
This will be solved by merging https://github.com/saschaholesch/opentracing-tutorial/ (just awaiting #62).

**Comment by Falco20019** [comment]
This will be fixed by https://github.com/yurishkuro/opentracing-tutorial/pull/21
