### ISSUE TITLE
Add size checking in transport

### ISSUE THREAD

**Issue by grounded042** [jaegertracing/jaeger-client-csharp#46]
Currently we do not check the buffer byte size in the `Jaeger.Transport.Thrift.Transport.JaegerThriftTransport` class. This can lead to the exception `Cannot flush closed transport. Message too long`. I have seen the exception when using the `JaegerUdpTransport`, but not the `JaegerHttpTransport` In other Jaeger client implementations there are checks to make sure exceptions like that do not happen: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/senders/ThriftSender.java

We should add a check. Also of note is that `TMemoryBufferClientTransport` is missing a reset method which could complicate things as we need that.

**Comment by yurishkuro** [comment]
not only client side exceptions - if the total UDP packet size exceeds 65000, the jaeger-agent will not be able to process it.

HTTP transport does not have these limitations.

**Comment by grounded042** [comment]
Thanks for the info @yurishkuro. I'm hoping to tackle this today.

**Comment by grounded042** [comment]
@yurishkuro is there a good way to determine the emit batch overhead? I ported `TestEmitBatchOverhead` to C# from https://github.com/jaegertracing/jaeger-client-go/blob/b7bacc465f385658dd3586f58810226776d2a4bf/transport_udp_test.go#L57 and I'm seeing a max overhead of 22. However, I'm unable to set the Client SeqId like in the go tests. I did not see anything in the Java client on how they determined the overhead. They have a different number `33` compared to the `30` in go, so I'm assuming it is not the same in each language.

**Comment by yurishkuro** [comment]
Yes, the technique is different by language due to different thrift APIs. I think the simplest thing is to use BINARY encoding, instead of COMPACT encoding, to avoid variable size numbers which were the cause of the complexity in the Go implementation. I think the impact on the message size from compact encoding is really minimal.

**Comment by grounded042** [comment]
Fixed in #47
