### ISSUE TITLE
Publish NuGet for new name

### ISSUE THREAD

**Issue by grounded042** [jaegertracing/jaeger-client-csharp#48]
We need to get the package published under it's new name(s) in NuGet. I know `Jaeger.Thrift` and `Jaeger.Thrift.VendoredThrift` will require a transfer of ownership on NuGet. @yurishkuro my last day at work is tomorrow. Any chance we could get this setup before the end of day on 4/6/2018?

**Comment by yurishkuro** [comment]
can you elaborate what I need to do?

**Comment by grounded042** [comment]
You'll need to have an account for Jaeger on NuGet.org. Once you create that I can add you as an owner on the two packages mentioned above. To get the rest publishing you will need to create an API Key on NuGet.org, sign into your AppVeyor account and encrypt the API Key using https://ci.appveyor.com/tools/encrypt, and put that encrypted value at https://github.com/jaegertracing/jaeger-client-csharp/blob/master/appveyor.yml#L40

**Comment by yurishkuro** [comment]
This is my account https://www.nuget.org/profiles/javajumbo

I assume it doesn't need to be called Jaeger?

**Comment by grounded042** [comment]
It does not. However the packages will publish as that user.

**Comment by grounded042** [comment]
@yurishkuro I've added you as an owner to the two packages already on NuGet.org. Once you add an API key to the AppVeyor config as I outlined above we can publish the rest of the packages automatically with the AppVeyor build.

**Comment by yurishkuro** [comment]
@grounded042 done

**Comment by yurishkuro** [comment]
@grounded042 I only have ownership of two packages on NuGet, but the build seems to be trying to upload more artifacts (and failed - https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp-gfqrm/build/6)
```
Collecting artifacts...
Found artifact 'artifacts\nuget\Jaeger.0.0.6.nupkg' matching 'artifacts\nuget\*.nupkg' path
Found artifact 'artifacts\nuget\Jaeger.Core.0.0.6.nupkg' matching 'artifacts\nuget\*.nupkg' path
Found artifact 'artifacts\nuget\Jaeger.Thrift.0.0.6.nupkg' matching 'artifacts\nuget\*.nupkg' path
Found artifact 'artifacts\nuget\Jaeger.Thrift.VendoredThrift.0.0.6.nupkg' matching 'artifacts\nuget\*.nupkg' path
Found artifact 'artifacts\nuget\Jaeger.Transport.Thrift.0.0.6.nupkg' matching 'artifacts\nuget\*.nupkg' path
Uploading artifacts...
[1/5] artifacts\nuget\Jaeger.0.0.6.nupkg (4,199 bytes)...100%
[2/5] artifacts\nuget\Jaeger.Core.0.0.6.nupkg (37,130 bytes)...100%
[3/5] artifacts\nuget\Jaeger.Thrift.0.0.6.nupkg (98,052 bytes)...100%
[4/5] artifacts\nuget\Jaeger.Thrift.VendoredThrift.0.0.6.nupkg (108,082 bytes)...100%
[5/5] artifacts\nuget\Jaeger.Transport.Thrift.0.0.6.nupkg (21,891 bytes)...100%
Deploying using NuGet provider
Publishing Jaeger.0.0.6.nupkg to https://www.nuget.org/api/v2/package...
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.
```

**Comment by grounded042** [comment]
Something is up with the API key

**Comment by yurishkuro** [comment]
I defined the key to cover `Jaeger.*`:

![image](https://user-images.githubusercontent.com/3523016/38438559-d189fc04-39a8-11e8-935d-d00a4a524421.png)

**Comment by grounded042** [comment]
@yurishkuro we also have the package `Jaeger`, so `Jaeger.*` would not cover that.

**Comment by yurishkuro** [comment]
That's what I meant, I don't have any other packages under my profile aside from these two. So I think the build is failing on permissions, not on the key itself being bad.

**Comment by yurishkuro** [comment]
![image](https://user-images.githubusercontent.com/3523016/38439131-868f0b0c-39aa-11e8-8eab-cee895b7ac2b.png)

**Comment by grounded042** [comment]
Hmm. Maybe you have to define it without any package restraints first and then add them after they are pushed up?

**Comment by grounded042** [comment]
My thinking is it might see that it can only push two packages so even though one of those is a brand new one it can't push it since it's not whitelisted.

**Comment by yurishkuro** [comment]
Trying a different key with `Jaeger*` glob.

**Comment by yurishkuro** [comment]
@grounded042 I think it worked

**Comment by grounded042** [comment]
It lives! https://www.nuget.org/packages/Jaeger/

**Comment by yurishkuro** [comment]
Unless there's something else that needs to be done, I am going to close this.
