### ISSUE TITLE
Jaeger and the `Microsoft.Extensions.*` stack (DI, Configuration, Logging)

### ISSUE THREAD

**Issue by cwe1ss** [jaegertracing/jaeger-client-csharp#57]
ASP.NET Core services are a one of the main targets of this library so it should be as easy as possible to set up a tracer there. We should therefore support the following modules/libraries:

* `Microsoft.Extensions.Configuration`: A developer should be able to configure Jaeger from environment variables, config files, etc. - The `Microsoft.Extensions.Configuration` library supports many different input sources.
* `Microsoft.Extensions.DependencyInjection`: A developer should be able to call `services.AddJaeger()`.
* `Microsoft.Extensions.Logging`: We already have a dependency on that.

With our already existing dependency on `Microsoft.Extensions.Logging` we are currently in a weird limbo state: People who do not use the new `Microsoft.Extensions.*` stack (e.g. ASP.NET WebForms) inherit many `Microsoft.Extensions.*` dependencies and can't easily consume the logs; people who already use the new `Microsoft.Extensions.*` stack (ASP.NET Core) get proper logging support but they don't get DI & Configuration support.

So the first thing I would like to discuss is if we should build this into the library (by adding additional dependencies) or if we want to move all `Microsoft.Extensions.*` stuff into a separate library:

### Scenario 1: Making the library `Microsoft.Extensions.*`-native

Adding additional dependencies would make it a `Microsoft.Extensions`-"native" library like e.g. Entity Framework Core, Identity Server. This would make it very easy to use Jaeger with ASP.NET Core (and any hosting framework that supports that stack) as they only have to add the main `Jaeger` package and call `services.AddJaeger()` and everything else will pretty much work automatically. 

But this obviously also limits its usage possibilities as it makes it much harder to use it in other scenarios.

### Scenario 2: Adding a new `Jaeger.Microsoft.Extensions` library

Thanks to the `Builder` types, we already have a decent initialization story, so it's already quite easy to use the library without dependencies on `Microsoft.Extensions.*`. One thing we don't yet have though (not even with #55 ) is Javas [Configuration.java](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/Configuration.java) type that supports configuration via environment variables. I did not port this because I wanted to have this discussion first.

To make it easier to use the library in ASP.NET Core, we could add a `Jaeger.Microsoft.Extensions` library (other naming suggestions welcome!) and provide the support for DI & Configuration there. The drawback with this is that people have to know about this additional library. 

If we go this way, we should also discuss whether or not we want to keep the `Microsoft.Extensions.Logging` dependency in the main library. Unfortunately, there's no "one global logging abstraction" in .NET so every alternative has drawbacks as well. Using the dependency-free [LibLog](https://github.com/damianh/LibLog) doesn't support `Microsoft.Extensions.Logging` and using our own interfaces requires people to build adapters. My proposal would be to just change the dependency to `Microsoft.Extensions.Logging.Abstractions` for now as that doesn't bring in any other `Microsoft.Extensions.*` dependencies. (Libraries should only rely on the `Microsoft.Extensions.*.Abstractions` libraries anyway)

To further illustrate this scenario, I have some initial code for this in the [cweiss/MsExtensions](https://github.com/jaegertracing/jaeger-client-csharp/tree/cweiss/MsExtensions)-branch (it's already based on #55).

------

I would favor scenario 2 with the separate library. This would ensure that the main Jaeger library can stay as close as possible to the Java code and that Jaeger can also be used properly outside of ASP.NET Core.

Your thoughts?

**Comment by yurishkuro** [comment]
Don't put too much weight to my opinion as I am not familiar with .NET ecosystem, but from what you described, as well as general design considerations, I would suggest:
  * having no `*.Extensions.*` dependencies in the core module, and
  * providing a separate module that has the dependencies and extra functionality

I am a bit surprised there is no standard logging API in .NET, but seeing how that's the case in most languages - not that surprised. It's worth pointing out that in most other languages the Jaeger clients do expose their own logging API. Yes, it requires bridges, but if the ecosystem has well-established logging APIs already then the bridges can be provided as additional modules. And the logging API needed by the client is really simple, just two methods, info and error.

Regarding fromEnv() builders, it was done manually in other languages as it's not that much code and it's not complicated. I am not sure it's worth having a dependency on some framework to support fromEnv().

**Comment by Falco20019** [comment]
Sorry for just answering now. I would strongly push towards scenario 2. We are using it with .NET Standard and only in some cases with ASP.NET Core. Therefore I would like to have the amount of dependencies at a minimum and use `Microsoft.Extensions.Logging.Abstractions`.

**Comment by mweinand** [comment]
Just to add some additional background, there is nothing stopping someone from using Microsoft.Extensions.Logging (and .Abstractions) in something other than ASP.Net Core.  It targets .net standard so its full compatible all over the ecosystem.  I have several .net framework 4.7 console apps using it.

**Comment by thzinc** [comment]
I see this issue hasn't been discussed for a few months. I'm working on a project where Microsoft.Extensions.Configuration support would be really useful, but I understand the hesitancy toward including a number of external dependencies.

I read through the `Jaeger.Configuration` class, and it seems that supplanting the `GetProperty` method with a delegate to resolve a `string` into a `string` (as `Environment.GetEnvironmentVariable(string name)` does) would allow someone integrating with the Jaeger client to resolve properties however they choose.

For those using Microsoft.Extensions.Configuration, given an `IConfiguration` instance, the resolver could be something like `(name) => configuration[name]`.

If it's not too obtrusive, I've created a fork where I've done this and will create a PR to further discuss this approach.

**Comment by paulomorgado** [comment]
The `Microsoft.Extensions.*` packages were developed by the ASP.NET team which, actually, started .NET Core but are not tied in any way to ASP.NET Core or even .NET Core. I've been using them for the past 2 years without ever having developed an ASP.NET Core or .NET Core application - lots of Windows services and ASP.NET MVC running on .NET Framework 4.6.2+.

`Microsoft.Extensions.Configuration.*` provides a good abstraction over configuration sources. You can use any file type or source (database?) you need. You can even pull configuration from environment variables.

Using `Microsoft.Extensions.Configuration.*` would work seamlessly with the reading from environment variables that is provided.

**Comment by yhvicey** [comment]
What about using lib's own logging interface, then wrap it in shim project? Everything related to `Microsoft.Extensions.*` can be put at shim project, including some adapter classes, and:

1. If users already used `Microsoft.Extensions.*` packages, they can consume this shim project directly;
1. Or, if users not satisfied with adapter classes we provided, they can build their own adapt classes;
1. If users not use any `Microsoft.Extensions.*` package, they can consume the lib package directly.

I think [Serilog](https://github.com/serilog/serilog) faced same problem and I think their solution (Standalone lib package without `Microsoft.Extensions.*`, and a shim project provides integration with `Microsoft.Extensions.*` packages, see [serilog-aspnetcore](https://github.com/serilog/serilog-aspnetcore)) works well for me.

**Comment by Falco20019** [comment]
We already use other `Microsoft.Extensions.*` libs, especially for Configuration right now. So I'm not sure anymore if we should try to get rid of them (needing to wrap configration AND logging) or if we should just keep them until there is a feature request from a use who really needs this. Since the initial post, .NET Framework is slowly dying in favor of .NET Core. And starting with .NET Framework 4.7 it's not even that ugly anymore. But I would still keep the issue open in case someone has a problem related to us using these libs directly.

In my project, we even added more usage of `Microsoft.Extensions.Logging` for by using [opentracing-contrib/csharp-logging](https://github.com/opentracing-contrib/csharp-logging/tree/feature/initial-draft), so we wouldn't get rid of it even when adding wrappers. It would just make it harder to use.
