### ISSUE TITLE
v0.0.10 release plan

### ISSUE THREAD

**Issue by cwe1ss** [jaegertracing/jaeger-client-csharp#62]
Now that #55 and #59 are merged, we should do a release soon.

My main open question is whether we should wait for the upcoming v0.12.0 release of OpenTracing? I'd like to release that one by the end of next week.

Anything else that should be included?

**Comment by Falco20019** [comment]
Let's wait for #61 and `OpenTracing v0.12.0`. Should be fine if it's just one more week.

**Comment by Falco20019** [comment]
Should be released tomorrow :) OpenTracing v0.12.0 for which we waited is released now. So just some reviews left.

Configuration will be easier with the new version. I also plan to get the tutorial for C# merged tomorrow.

**Comment by ScottGuymer** [comment]
Ok thats good news. Ill configure against a local build for now.

Im also happy to contribute back anything I can too.

**Comment by Falco20019** [comment]
@cwe1ss I think we now have everything ready for v0.0.10 👍 Can you push the artifacts to NuGet?

**Comment by cwe1ss** [comment]
I couldn't do the release because the NuGet credentials in the appveyor.yml seem to be wrong ([build output](https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp/build/19)). I will create a separate issue with instructions for Yuri.

**Comment by Falco20019** [comment]
Very strange, since we changed it [here](https://github.com/jaegertracing/jaeger-client-csharp/issues/48#issuecomment-379360086) the last time. Thanks for informing @yurishkuro

**Comment by cwe1ss** [comment]
The release succeeded this time! 🍻 

As we're no longer using the `Jaeger.Core` and `Jaeger.Transport.Thrift` packages, I'd like to unlist all previous Jaeger versions on NuGet.org to reduce confusion. Any objections?

**Comment by Falco20019** [comment]
Yes, I think unlisting them should be the cleanest option.

**Comment by cwe1ss** [comment]
I unlisted these packages.
