### ISSUE TITLE
Create NuGet organization and assign permissions

### ISSUE THREAD

**Issue by cwe1ss** [jaegertracing/jaeger-client-csharp#66]
@yurishkuro We currently can't deploy because the NuGet credentials in our appveyor.yml file are wrong. Could you please do the following things - this will ensure that we have a similar setup like the [OpenTracing NuGet account](https://www.nuget.org/profiles/OpenTracing) where multiple people have access to the NuGet packages:

* Login on nuget.org with your "javajumbo" account
* [Add a new organization](https://www.nuget.org/organization/add) and name it e.g. "Jaeger", "JaegerTracing", ... (whatever you like and is available).
* Add this new organization as an "owner" to all "Jaeger"-packages. You can do this on this page: https://www.nuget.org/account/Packages
* [Add administrators](https://www.nuget.org/account/Organizations) to the organization. My NuGet account name would be "cwe1ss". Not sure what @Falco20019 's account name is. (I can always add him later once I'm an admin)

As you've already made me an admin on the "jaegertracing"-AppVeyor account, I'll then do everything else (I'll create the new NuGet API key and add it to AppVeyor and I'll update the appveyor.yml file)

**Comment by Falco20019** [comment]
My NuGet user name is also `falco20019`.

**Comment by yurishkuro** [comment]
added to https://www.nuget.org/organization/JaegerTracing

**Comment by cwe1ss** [comment]
thank you @yurishkuro! I'll take care of the rest!
