### ISSUE TITLE
Self referencing loop when using LoggingReporter

### ISSUE THREAD

**Issue by Falco20019** [jaegertracing/jaeger-client-csharp#68]
With the dropping of [IJaegerCoreSpan](https://github.com/jaegertracing/jaeger-client-csharp/pull/55/files#diff-5cf05b611581a56a5de3cb4d55a24902L17) in #55, the `JsonIgnore` attribute from `Tracer` was removed. This is needed to resolve a referencing loop in `JsonConvert` used by `LoggingReporter`. Right now, logging throws this exception:

**Newtonsoft.Json.JsonSerializationException:** 'Self referencing loop detected for property 'Span' with type 'Jaeger.Span'. Path 'Tracer.ScopeManager.Active'.'

This happens, when we are logging the active Span when finishing a scope from `StartActive`. We have two options to resolve this.

This can be easily fixed by adding the `JsonIgnore` attribute to the `Tracer` property in the `Span` implementation.

**Comment by cwe1ss** [comment]
jaeger-client-java [uses `toString()` in the logger](https://github.com/jaegertracing/jaeger-client-java/blob/3ffaf9d753fe96a1925729d42fd371a0a166c03b/jaeger-core/src/main/java/io/jaegertracing/reporters/LoggingReporter.java#L42) which then [outputs a few details about the span](https://github.com/jaegertracing/jaeger-client-java/blob/3ffaf9d753fe96a1925729d42fd371a0a166c03b/jaeger-core/src/main/java/io/jaegertracing/Span.java#L144). Seems like I missed that on that PR. Might be better than serializing the whole span?!

**Comment by Falco20019** [comment]
Ok, so I assumed that you kept it on purpose from `LetsTrace`. So in that case, it would really be better to just use the `ToString` to keep it similar to `jaeger-client-java`. I'm just adjusting https://github.com/saschaholesch/opentracing-tutorial/tree/csharp to get it ready for merging. Therefore I'm stumbling over a lot of the console logging stuff.
