### ISSUE TITLE
Move to Jaeger Org

### ISSUE THREAD

**Issue by grounded042** [jaegertracing/jaeger-client-csharp#7]
Hey @yurishkuro we've been chatting at Chatham about getting tracing implemented and we've got a couple of questions about LetsTrace once we move it over to the Jaeger Org. We had talked before about ownership over the backlog (https://github.com/jaegertracing/jaeger/issues/578#issuecomment-370961906). 

We're still wondering about the backlog and contributors - we have a skilled C# team that is going to be using the library internally and who is willing to contribute, speed along, and maintain the repo. It seems like there are not very many C# developers in the Jaeger Org at this point and we're concerned that LetsTrace won't get the love it needs once moved. Will we be considered maintainers once the move occurs? Or will we have to be forking and submitting PRs to be reviewed by someone in the org?

**Comment by yurishkuro** [comment]
The way we structure Jaeger repos is that there is a core team of maintainers, plus additional maintainers per individual repo. You should definitely be in the latter category. I'd leave it up to you to decide who exactly needs to have full commit rights at the time of the move.

**Comment by grounded042** [comment]
Perfect @yurishkuro. That's what I was thinking, but wanted to make sure.

**Comment by grounded042** [comment]
I'm going to add some obsolete tags and bump the version so we can get this on Nuget. Then we should be good to move over to Jaeger org @yurishkuro. 

In prep for that you'll probably want to have a https://www.nuget.org account set up so we can publish the packages. Also I think we probably will have to use Appveyor unless we can get ILRepack working on Linux / MacOS.

**Comment by grounded042** [comment]
@cwe1ss, @Falco20019, @yurishkuro I'm going to go ahead and add you guys to this project as we are at a good state to get moved over to the Jaeger org in the next couple of days.

Before we move I'd like to get things renamed so that right before the move we can do that version bump that has the obsolete info. Once we are over in the Jaeger org the Nuget deploy key on this repo will not work in AppVeyor since it is tied to the Chatham AppVeyor account. There is a discussion related to this over in #33.

**Comment by yurishkuro** [comment]
Ping me when ready to move. 

The deploy key issues are probably easier to sort out once in the new location.

**Comment by grounded042** [comment]
@yurishkuro I just merged the rename in #38. We are ready to move!

**Comment by yurishkuro** [comment]
Moved!!   Great work, everyone.
