### ISSUE TITLE
Example WebApi not building

### ISSUE THREAD

**Issue by luigiberrettini** [jaegertracing/jaeger-client-csharp#8]
The Tracer constructor is private and a builder [should be used](https://github.com/Chatham/LetsTrace/blob/e680cf0a3679e5a40295e9ab386c84fb61ec3578/examples/LetsTrace.Example.WebApi/TracingWrapper.cs#L16) to create a tracer

**Comment by grounded042** [comment]
Hey @luigiberrettini, sorry about that. We'll get to that hopefully this week, though for now we are focusing on pulling in a big branch to LetsTrace.Jaeger. If you have a PR I'd be happy to take a look.

**Comment by marcusdb** [comment]
Hello @grounded042 how can I see the branch you guys are going to pull? Is this a fork? I don´t see it anywhere on the project branches

**Comment by grounded042** [comment]
@marcusdb the branch we are looking to pull into LetsTrace.Jaeger is https://github.com/Falco20019/LetsTrace.Jaeger/tree/improvements. You might also find this issue of interest https://github.com/Chatham/LetsTrace.Jaeger/issues/2 as it outlines the plans moving forward to combine the two and move them over to the Jaeger org.

**Comment by grounded042** [comment]
As of #38 the Example WebAPI builds.
