### ISSUE TITLE
Correlating traces between csharp and java clients

### ISSUE THREAD

**Issue by ScottGuymer** [jaegertracing/jaeger-client-csharp#81]
Im trying to set up a demo to demonstrate tracing across various languages supported by opentracing.

I am running into an issue when trying to get a trace between csharp and java.

I think i have tracked it down to the fact that the traceid generated by the chsarp client is too long.

It seems that the traceid is 32 characters long in the generated header but all the traceids generated by both java and python are only 16 character.

csharp example
e25d900a5c462be7cafa992548dc6d0d

java example
cafa992548dc6d0d

I havent been quite able to get to the bottom of why this might be and what the issue is with the longer id on the java end as it seems to cause an issue and make the java client create a new traceid and breaks the cross process tracing.

I think i have tracked the cause down to the tostring method on TraceID here https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/TraceId.cs#L38

But im not sure if this is right or wrong.

**Comment by yurishkuro** [comment]
128bit IDs are not yet uniformly supported in all Jaeger clients. Csharp client should default to generating 64bit IDs, with opt-in for 128bit.

**Comment by ScottGuymer** [comment]
Im not aware that i have changed any defaults to make it use a 123bit ID.

Not even sure where i would do that! 😄

**Comment by ScottGuymer** [comment]
Or are you saying that it _should_ but doesnt currently..

**Comment by ScottGuymer** [comment]
I can see the issue in the java implementation here https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/SpanContext.java#L125

it expects the traceid to be 16 characters only

**Comment by Falco20019** [comment]
Yes, right now we are using always 128bit. I will create a PR to fix this in a second. C# has to use 64bit since this is the common one.

**Comment by ScottGuymer** [comment]
That was super fast! Nice work

**Comment by Falco20019** [comment]
@ScottGuymer Version `v0.1.1` is now online on NuGet.
