### ISSUE TITLE
ChildOf reference doesn't work

### ISSUE THREAD

**Issue by Marfusios** [jaegertracing/jaeger-client-csharp#87]
Hello, 

thank you for the library. I continue to integrate Jaeger into our system, but I struggle with setting a reference to a parent span. 
We are using Linkerd as a service mesh which sends us open tracing coordinates via HTTP header.

>It’s base64 encoded and formatted as: spanId:8 parentId:8 traceId:8 flags:8' (big-endian). 
[link](https://discourse.linkerd.io/t/logging-to-zipkin/672)

I managed to parse that coordinates and create parent context with method `SpanContext.ContextFromString(decodedString)` and reference it by `span.AddReference(References.ChildOf, parentCtx)`. 
But after sending it through HTTP sender (whether it was sent), I'm **not able to find** any of my trace logs in Jaeger GUI (without that reference, it is visible at least under own service category). 

Are there any logs which could help me to locate the issue?  
Do you see any obvious problem with my code below? 

More info: 

Code: 

```csharp
        public ITracer Tracer { get; }

        public ISpanBuilder BuildSpan(string operation)
        {
            var span = Tracer?.BuildSpan(operation);
            if (span == null)
                return null;

            var coordinates = _correlation.GetTracingCoordinates();
            if (!string.IsNullOrWhiteSpace(coordinates))
            {
                var parentCtx = GetParentContextFrom(coordinates);
                if (parentCtx != null)
                    span.AddReference(References.ChildOf, parentCtx);
            }       
            return span;
        }

        private static SpanContext GetParentContextFrom(string coordinates)
        {
            try
            {
                var decoded = Convert.FromBase64String(coordinates);
                var splitted = Split(decoded, 8).Select(ByteArrayToString).ToArray();
                var decodedString = string.Join(":", splitted[2], splitted[1], splitted[0], splitted[3]);
                var ctx = SpanContext.ContextFromString(decodedString);
                return ctx;
            }
            catch
            {
                return null;
            }
        }
```

Trace id: `7d04838dcc710f8f`
Coordinates: `UmfYme1Ztni5uqIlE9LJin0Eg43McQ+PAAAAAAAAAAY=`

Runtime values: 
![image](https://user-images.githubusercontent.com/3494837/41475040-f3969c84-70bd-11e8-937a-dd05ca8c513e.png)

Jaeger gui:
![image](https://user-images.githubusercontent.com/3494837/41475152-4342c802-70be-11e8-80c5-1886d2dd42c5.png)

Logs with reference:
**Nothing**

Logs without reference:
```
info: Jaeger.Configuration[0]
      Initialized Tracer(ServiceName=DataAccessSample, Version=CSharp-0.1.1.0, Reporter=RemoteReporter(Sender=HttpSender), Sampler=ConstSampler(True), IPv4=-1062683071, Tags=[jaeger.version, CSharp-0.1.1.0], [hostname, DESKTOP-7OEFQ0F], [ip, 192.168.190.65], ZipkinSharedRpcSpan=False, ExpandExceptionLogs=False)
```

**Comment by Falco20019** [comment]
The problem is, that your parent context has the `SpanContextFlags` set to `0x06`. This sets the `Debug` flag but not the `Sampled` flag. Make sure to set `SpanContextFlags.Sampled` (`0x01`) if you want to have a span sampled. The sampler given to the tracer is only for generating new spans. Parent spans dictate that for incoming spans.

If you want to use the sampler of the tracer to decide if it's to be sampled, you can change your `GetParentContextFrom` like this:
```
var ctx = SpanContext.ContextFromString(decodedString);
if (Tracer.Sampler.Sample(operation, ctx.TraceId).IsSampled)
  ctx = ctx.WithFlags(ctx.Flags | SpanContextFlags.Sampled);
return ctx;
```

**Comment by Marfusios** [comment]
Thank you for an explanation, it works
