### ISSUE TITLE
Admin-rights for @Falco20019

### ISSUE THREAD

**Issue by cwe1ss** [jaegertracing/jaeger-client-csharp#93]
Unfortunately, I'm currently really busy at work so I have very limited time for contributions :( 

I therefore like to give @Falco20019 admin-rights for this repo. This allows him to e.g. squash a stuck PR (see #91) He already has write-access.

any concerns?

/cc @yurishkuro

**Comment by yurishkuro** [comment]
+1. Let me know if you need help to do that.

**Comment by cwe1ss** [comment]
Done! Thx for the quick response!
