### ISSUE TITLE
When is 0.2.0 expected to be released?

### ISSUE THREAD

**Issue by rwkarg** [jaegertracing/jaeger-client-csharp#95]
## Requirement - what kind of business use case are you trying to solve?

Use Jaeger version without unbounded CPU utilization bug (see PR #91)

## Problem - what in Jaeger blocks you from solving the requirement?

The currently published 0.1.1 package does not contain the above bug fix

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Provide guidance on when to expect 0.2.0 or some other package release that contains the fix in the above PR.

## Any open questions to address

----

**Comment by Falco20019** [comment]
I pushed #72 to v0.3.0 and released v0.2.0 right now since it’s not blocking the release. The package should be available soon on NuGET. It’s validating right now.

**Comment by rwkarg** [comment]
Verified 0.2.0 is available on NuGet. Thanks!
