### ISSUE TITLE
Propagation format is seemingly only configurable through environment variables

### ISSUE THREAD

**Issue by oliverroer** [jaegertracing/jaeger-client-csharp#97]
## Requirement - what kind of business use case are you trying to solve?

[Integration with Istio, by propagating zipkin headers.](https://istio.io/docs/tasks/telemetry/distributed-tracing/#understanding-what-happened)

## Problem - what in Jaeger blocks you from solving the requirement?

It is not clear how to configure the propagation to use the zipkin format.
The only approach I've found is to use environment variables.
Since I'm interesting in configuring this through C# code, I'm currently using an approach like this:

```
...
Environment.SetEnvironmentVariable("JAEGER_PROPAGATION", "b3");
Configuration config = Configuration.FromEnv(loggerFactory);
ITracer tracer = config.GetTracer();
...
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Provide a way to configure the propagation, directly in C#.
If there already is, I haven't been able to figure it out, and would appreciate some documentation or examples that address this. 😄

**Comment by rwkarg** [comment]
In the Tracer.Builder you can call .RegisterCodec(...) to add a codec (like B3TextMapCodec) at runtime.

**Comment by Falco20019** [comment]
You can use `config.GetTracerBuilder()` to get the `Tracer.Builder` that @rwkarg mentioned. But I think it would also be nice to have it in the `Configuration`. Seems somewhat strange if only some of them can be accessed directly.

**Comment by oliverroer** [comment]
So, let's say I have a scenario where I want to:
- set my service name
- set the agent host
- set the sampler type to const
- set the propagation to b3+jaeger
- keep the rest default

First, I achieved this in the following way:

```csharp
Environment.SetEnvironmentVariable("JAEGER_SERVICE_NAME", "someservicename");
Environment.SetEnvironmentVariable("JAEGER_AGENT_HOST", "someagenthost");
Environment.SetEnvironmentVariable("JAEGER_SAMPLER_TYPE", "const");
Environment.SetEnvironmentVariable("JAEGER_PROPAGATION", "b3,jaeger");
Configuration config = Configuration.FromEnv(someLoggerFactory);
ITracer tracer = config.GetTracer();
```

Based on your answers, and looking around the code base, I've arrived at this alternative approach, which seems to also work for me:

```csharp
ISender sender = new UdpSender("someagenthost", 0, 0);
IReporter reporter = new RemoteReporter.Builder()
    .WithSender(sender)
    .Build();

ISampler sampler = new ConstSampler(true);

ITracer tracer = new Tracer.Builder("someservicename")
    .WithReporter(reporter)
    .WithSampler(sampler)
    .RegisterCodec(BuiltinFormats.HttpHeaders, new TextMapCodec(true))
    .RegisterCodec(BuiltinFormats.HttpHeaders, new B3TextMapCodec())
    .RegisterCodec(BuiltinFormats.TextMap, new TextMapCodec(false))
    .RegisterCodec(BuiltinFormats.TextMap, new B3TextMapCodec())
    .Build();
```

Did I miss anything?

**Comment by Falco20019** [comment]
I would prefer it that way:
```csharp
Environment.SetEnvironmentVariable("JAEGER_PROPAGATION", "b3,jaeger");
var senderConfiguration = new Configuration.SenderConfiguration(loggerFactory)
	.WithAgentHost("someagenthost");
var reporterConfiguration = new Configuration.ReporterConfiguration(loggerFactory)
	.WithSender(senderConfiguration);
var samplerConfiguration = new Configuration.SamplerConfiguration(loggerFactory)
	.WithType(ConstSampler.Type)
	.WithParam(1);
var tracer = new Configuration(serviceName, loggerFactory)
	.WithSampler(samplerConfiguration)
	.WithReporter(reporterConfiguration)
	.WithCodec(CodecConfiguration.FromEnv(loggerFactory))
	.GetTracer();
```

Or to get completely away without environmental variables:
```csharp
var senderConfiguration = new Configuration.SenderConfiguration(loggerFactory)
	.WithAgentHost("someagenthost");
var reporterConfiguration = new Configuration.ReporterConfiguration(loggerFactory)
	.WithSender(senderConfiguration);
var samplerConfiguration = new Configuration.SamplerConfiguration(loggerFactory)
	.WithType(ConstSampler.Type)
	.WithParam(1);
var httpHeaderCodec = new CompositeCodec<BuiltinFormats.HttpHeaders> { new TextMapCodec(true), new B3TextMapCodec() };
var textMapCodec = new CompositeCodec<BuiltinFormats.TextMap> { new TextMapCodec(false), new B3TextMapCodec() };
var tracer = new Configuration(serviceName, loggerFactory)
	.WithSampler(samplerConfiguration)
	.WithReporter(reporterConfiguration)
	.WithCodec(CodecConfiguration.FromEnv(loggerFactory))
	.GetTracerBuilder()
	.RegisterCodec(BuiltinFormats.HttpHeaders, httpHeaderCodec)
	.RegisterCodec(BuiltinFormats.TextMap, textMapCodec)
	.Build();
```

The problem right now, is that you are redifining the Codec with `RegisterCodec` instead of adding it. You need to create a `CompositeCodec` first. `CodecConfiguration` is doing this for you, but it's missing a public constructor that allows you to define the propagation. Would be better to add one which has a `param Propagation[] propagations` input. This would let us drop the environment variable in the first example.

**Comment by oliverroer** [comment]
Your second example still contains the line `.WithCodec(CodecConfiguration.FromEnv(loggerFactory))`.
Is that intentional or an accident?

I agree that the proposed third example looks cleaner. :smile:

**Comment by Falco20019** [comment]
No was not intentional :) edited it for other people reading it. Will have a look at it beginning of next week.
