### ISSUE TITLE
Http Thrift requests without Content-Type headers are rejected 

### ISSUE THREAD

**Issue by rwkarg** [jaegertracing/jaeger-client-csharp#99]
## Requirement - what kind of business use case are you trying to solve?

Report Spans via Http Thrift requests (port 14268)

## Problem - what in Jaeger blocks you from solving the requirement?

Recent versions of the Jaeger backend reject Http Thrift requests that do not contain a `Content-Type: application/x-thrift` header.
An Http 400 response is returned with the following message:
`Cannot parse content type: mime: no media type`

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Include the expected header in Http Thrift requests

**Comment by rwkarg** [comment]
This was addressed by #101

**Comment by Falco20019** [comment]
Sorry for the delays but I‘m low on time right now :( wanted it as part of v0.3 but just moved it to v0.2.1 which should release the next couple of minutes.

**Comment by Aaronontheweb** [comment]
@Falco20019 thanks! Just upgraded. I really appreciate you all responding so quickly. This solved my problem.
